### ISSUE TITLE
Failing to copy the build plugin to directory "plugin-build"

### ISSUE THREAD

**Issue by modlfo** [VCVRack/rack-plugin-toolchain#15]
I'm having a problem in the last step of building a plugin. This is the error I get 
```
cp /home/build/plugin-src/dist/*.vcvplugin plugin-build/
cp: cannot create regular file 'plugin-build/Geodesics-Vultiverse-2.0.0-win.vcvplugin': Permission denied
```
I have tried a few things, like changing the permissions of the directory and manually creating it before invoking the build.

Any idea on how to solve this? 

I'm running docker on an Ubuntu 21.04.

**Comment by modlfo** [comment]
I just figured it out.

When passing the argument.
```
--volume=$(PWD)/$(PLUGIN_BUILD_DIR):/home/build/rack-plugin-toolchain/$(PLUGIN_BUILD_DIR)
```
The `$(PWD)` returns an empty string for me. So it is not mapping the correct volume.

**Comment by cschol** [comment]
OK. That's strange. Are you using bash?

**Comment by modlfo** [comment]
Yes. If I run `$ echo $PWD` I get the expected result. I'm not sure why when running `make` the variable has no value. Could it be related to me having to run docker with sudo?: `make -j8 docker-plugin-build PLUGIN_DIR=...`

**Comment by cschol** [comment]
Yes. You should not have to run Docker with `sudo`. Check the Docker documentation to allow the current user to run Docker without needing `sudo`.

Reference: https://docs.docker.com/engine/install/linux-postinstall/

**Comment by modlfo** [comment]
Thanks! it's working now.
