### ISSUE TITLE
SDK version update

### ISSUE THREAD

**Issue by jpnielsen** [VCVRack/rack-plugin-toolchain#16]
[`RACK_SDK_VERSION := 2.0.2`](https://github.com/VCVRack/rack-plugin-toolchain/blob/4a80d58ae6951c29ebe0592fad34c561d3c66922/Makefile#L19)

please update

please provide script to update existing docker image to latest SDK.

**Comment by jpnielsen** [comment]
I know you must have other things to do - here's how I do it for now:

```
cd rack-plugin-toolchain
make docker-run
// in docker shell:
sed -i 's/^RACK_SDK_VERSION := .*$/RACK_SDK_VERSION := 2.0.5/g' Makefile
rm -rf Rack-SDK-lin Rack-SDK-mac Rack-SDK-win
make rack-sdk-lin rack-sdk-mac rack-sdk-win
exit
```

**Comment by cschol** [comment]
SDK version has been updated.

The above command does not do what you think it does. You need to update the SDK version in the `image` and not just in a running `container`.

Once you have updated the `container`, you can use `docker commit` to write the changes to an image that you can use for future builds.

We are looking into a way to update the SDK more easily without having to rebuild the entire toolchain.

**Comment by jpnielsen** [comment]
Thank you
