### ISSUE TITLE
make docker-build fails - Can't find libc++ headers

### ISSUE THREAD

**Issue by xyzeugene** [VCVRack/rack-plugin-toolchain#20]
I am running Fedora 35 and with the command : 

make docker-build

And the error I get is : 

========
Given SDK does not contain libc++ headers (-stdlib=libc++ test may fail)
You may want to re-package your SDK using 'tools/gen_sdk_package.sh' on macOS

testing x86_64-apple-darwin20.2-clang++ -stdlib=libc++ -std=c++11 ... failed (ignored)

testing x86_64h-apple-darwin20.2-clang ... osxcross: error: cannot find libc++ headers
osxcross: error: while detecting target
failed (ignored)
testing x86_64h-apple-darwin20.2-clang++ ... osxcross: error: cannot find libc++ headers
osxcross: error: while detecting target
failed (ignored)

testing arm64-apple-darwin20.2-clang ... osxcross: error: cannot find libc++ headers
osxcross: error: while detecting target
failed (ignored)
testing arm64-apple-darwin20.2-clang++ ... osxcross: error: cannot find libc++ headers
osxcross: error: while detecting target
failed (ignored)

testing arm64e-apple-darwin20.2-clang ... osxcross: error: cannot find libc++ headers
osxcross: error: while detecting target
failed (ignored)
testing arm64e-apple-darwin20.2-clang++ ... osxcross: error: cannot find libc++ headers
osxcross: error: while detecting target
failed (ignored)

testing x86_64-apple-darwin20.2-clang ... osxcross: error: cannot find libc++ headers
osxcross: error: while detecting target

exiting with abnormal exit code (1)

**Comment by xyzeugene** [comment]
FWIW I also downloaded MacOSX11.1.sdk.tar.xz

**Comment by cschol** [comment]
You can't download the SDK. You have to generate it.
