### ISSUE TITLE
Error in loading plugin on windows

### ISSUE THREAD

**Issue by docb** [VCVRack/rack-plugin-toolchain#23]
hi,
i have sucessfully compiled a windows vcvplugin with the toolchain.
when starting Rack on windows i get the following error message:
[0.149 warn src/plugin.cpp:194 loadPlugin] Could not load plugin C:/Users/User/Documents/Rack2/plugins/dbRackCsound: Failed to read init() symbol in C:/Users/User/Documents/Rack2/plugins/dbRackCsound/plugin.dll
What does this error message mean? (The plugin could obviously be loaded, otherwise a different error message would appear).
The plugin is here:
https://github.com/docb/dbRackCsound
https://github.com/docb/dbRackCsound/releases/tag/2.0.0

Note that it runs on mac and linux and the heavy thing is to link statically Csound (libcsound64.a which i compiled for windows with mingw).
May be some one has an idea.
Thanks and Best regards,
Christian

**Comment by cschol** [comment]
Moving discussion: https://github.com/docb/dbRackCsound/issues/1

**Comment by docb** [comment]
The discussion was incorrectly moved to dbRackCsound. So still the question, has some one any idea why the "init" symbol is not found after loading the plugin?

**Comment by cschol** [comment]
First, we need to ensure that the plugin can build with the latest version of the toolchain. Until that is not happening, we don't assume there is an issue with the toolchain. Once it is building on my system and there are still errors, we can reopen this discussion.
