### ISSUE TITLE
make toolchain-all Fails with zlib download issue

### ISSUE THREAD

**Issue by kockie69** [VCVRack/rack-plugin-toolchain#24]
The build tries to get zlib (I think it is looking for an old version):

[ERROR]    zlib: download failed
[ERROR]
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Retrieving needed toolchain components' tarballs'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_Abort[scripts/functions@487]
[ERROR]  >>        called from: CT_DoFetch[scripts/functions@2130]
[ERROR]  >>        called from: CT_PackageRun[scripts/functions@2090]
[ERROR]  >>        called from: CT_Fetch[scripts/functions@2201]

**Comment by cschol** [comment]
Confirmed. This is for the Windows `crosstool-ng` build. I will investigate.

**Comment by cschol** [comment]
Reference: `crosstool-ng` issue: https://github.com/crosstool-ng/crosstool-ng/issues/1832

**Comment by kockie69** [comment]
Thanks, so I manually can change the config file from what I saw in the other chat . Otherwise I will wait for official fix. Wanted to see if I can get my LFM module built this way.
