### ISSUE TITLE
What is a good way to turn off strip from a toolchain build

### ISSUE THREAD

**Issue by squinkylabs** [VCVRack/rack-plugin-toolchain#6]
I often find that toolchain builds crash when my regular dev builds don't. How can I turn off stripping so that I can try to debug these crashes? btw: here is how I am doing it now:

I modify the main makefile for the toolchain like so:
```
##  HAX
## plugin-build-win: export STRIP := x86_64-w64-mingw32-strip
plugin-build-win: export STRIP := foo-bar
```

That causes the build to bomb out before it strips and deletes, leaving my un-stripped plugin.dll in $PLUGIN_DIR/plugin.dll.

**Comment by cschol** [comment]
Currently, there is no facility to do this easily. I would recommend you build the Docker image of the toolchain, which has all of the correct compiler versions installed and then use `PLUGIN_DIR=<src location> make docker-run` to launch it. Then you can manually execute builds. Stripping is implemented in the **Rack** part of the build process and probably always require a hack like above to disable.

**Comment by squinkylabs** [comment]
thanks!
