### ISSUE TITLE
should the rack-plugin-toolchain be updated?

### ISSUE THREAD

**Issue by squinkylabs** [VCVRack/rack-plugin-toolchain#7]
if so, it it the same prodcess as other rack thing? update the deps, pull main, build deps, build main?

**Comment by cschol** [comment]
Updated how? As in new versions of the toolchain components?

**Comment by squinkylabs** [comment]
Yeah, I was wondering if deps need updating or if anything had changed. I want to be sure my local version is up to date. But it looks like nothing has changed in a long time.

fwiw I continue to have really bad crashing issues with the toolchain. I'll open a new issue about that.

**Comment by cschol** [comment]
There has been no update to the tool chain since its initial release and there likely won't be an update before v2 release.

**Comment by squinkylabs** [comment]
thanks!
